"""Forced-rerun regression for databases retaining legacy question IDs."""

from __future__ import annotations

from pathlib import Path

from pipeline.database import Database
from pipeline.process import process_pdf
from tests.test_duplicate_question_identity import _duplicate_detection, _write_two_page_pdf


def test_forced_rerun_uses_persisted_legacy_id_for_fts_and_attachments(
    config, tmp_path: Path, monkeypatch
):
    from pipeline.detect import QuestionDetector

    monkeypatch.setattr(QuestionDetector, "detect", lambda self, doc: _duplicate_detection())
    pdf = _write_two_page_pdf(
        tmp_path / "legacy" / "SharedSchool_2024_2U_Test.pdf", "Legacy paper"
    )
    first = process_pdf(config, pdf)
    db = Database(config.paths["database"])
    db.init_schema()

    canonical_id = f"{first['paper_id']}-q1"
    legacy_id = "imported-before-occurrence-identity"
    with db.conn() as connection:
        # Model an upgraded corpus whose logical row kept a historical primary
        # key. The existing attachment ID intentionally still contains the
        # canonical candidate ID generated by a previous processor version.
        connection.commit()
        connection.execute("PRAGMA foreign_keys = OFF")
        try:
            connection.execute(
                "UPDATE answers SET question_id=? WHERE question_id=?",
                (legacy_id, canonical_id),
            )
            connection.execute(
                "UPDATE questions SET id=? WHERE id=?", (legacy_id, canonical_id)
            )
            connection.commit()
        finally:
            connection.execute("PRAGMA foreign_keys = ON")

    rerun = process_pdf(config, pdf, force=True, db=db)
    assert rerun["questions"] == 2

    rows = db.questions_for_paper(first["paper_id"])
    assert {row["id"] for row in rows} == {
        legacy_id,
        f"{first['paper_id']}-q1--occurrence-2",
    }
    with db.conn() as connection:
        attachments = connection.execute(
            "SELECT id, question_id, source_page FROM answers WHERE paper_id=? ORDER BY source_page",
            (first["paper_id"],),
        ).fetchall()
        assert len(attachments) == 2
        assert attachments[0]["question_id"] == legacy_id
        assert attachments[0]["id"].startswith(canonical_id)
        assert connection.execute("PRAGMA foreign_key_check").fetchall() == []
        fts_ids = {
            row[0]
            for row in connection.execute(
                "SELECT question_id FROM questions_fts WHERE question_id IN (?, ?)",
                (canonical_id, legacy_id),
            ).fetchall()
        }
    assert fts_ids == {legacy_id}

    matches, count = db.search_questions("first value")
    assert count == 1
    assert matches[0]["id"] == legacy_id
    db.close()
